apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: bitnami
  kubeconfigRef:
    secret:
      name: vc-config-vcluster
      key: config.yaml
  targetNamespace: nginx
  install:
    createNamespace: true
  values:
    service:
      type: ClusterIP
