apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-2
  namespace: vcluster
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "13.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: vcluster
  kubeConfig:
    secretRef:
      name: vcluster-mock-config
      key: config
  targetNamespace: nginx
  values:
    service:
      type: ClusterIP
    podSecurityContext:
      enabled: true
      runAsUser: 1001
      fsGroup: 1001
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      enabled: true
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
