apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: vcluster  # This is where the HelmRelease resource will be created
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "13.x"  # Specify a version compatible with your cluster
      sourceRef:
        kind: HelmRepository
        name: bitnami
  kubeConfig:
    secretRef:
      name: vcluster-mock-config
      key: config
  targetNamespace: nginx  # This is where the nginx chart will be installed
  install:
    createNamespace: true  # This will create the target namespace if it doesn't exist
  values:
    service:
      type: ClusterIP
