apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: vcluster
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "13.x"  # Specify a version compatible with your cluster
      sourceRef:
        kind: HelmRepository
        name: bitnami
  kubeConfig:
    secretRef:
      name: vcluster-mock-config
      key: config
  targetNamespace: nginx
  install:
    createNamespace: true
  values:
    service:
      type: ClusterIP
